services:
  minio:
    container_name: minio-service
    image: minio/minio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '${MINIO_PORT}:9000'
      - '${MINIO_ADMIN_PORT}:9001'
    env_file: 'yours.env'
    volumes:
      - 'minio_data:/data'
      - '${MINIO_LOGS_DIR}:/logs'
    command: server /data --console-address ":9001"    

  postgres:
    container_name: postgres-service
    image: gostream-postgres-image:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile.postgres
      tags:
      - "gostream-postgres-image:latest"
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file: 'yours.env'
    environment:
      PGDATA: /var/lib/postgresql/data/gostream
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf'
      - '${POSTGRES_LOGS_DIR}:/logs'
    
volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
